export const SET_POKEMONS = 'SET_POKEMONS';
export const SET_FILTER_POKEMON = 'SET_FILTER_POKEMON';
export const SET_POKEMON = 'SET_POKEMON';
export const SYNC_INPUT = 'SYNC_INPUT';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const CLOSE_POKEMONDETAILS_CONTAINER = 'CLOSE_POKEMONDETAILS_CONTAINER';
